fix(core): Update Spark version to 2.3.2 (#1145)
Note: Currently, docker part is not verified.

Due to update, multiple testcases failed with
NoSuchMethodError with following errors
- io.netty.buffer.PooledByteBufAllocator.metric()
  Netty was updated to fix this.
- net.jpountz.lz4.LZ4BlockInputStream.<init>
  cassandra-unit dependency was bringing old version
  of lz4 which was 1.3.0. Spark upgraded this library
  in new version and cannot work without 1.4.0. So,
  excluded the 1.3.0 from cassandra-unit.
  https://issues.apache.org/jira/browse/SPARK-21276
- ImportError: No module named py4j.java_gateway
  Updated the py4j version to 0.10.7, the hint for
  this version comes from what Spark package internally
  uses. Inside spark 2.3.2 package, the right py4j
  version can be figured out by going to
  spark_package_dir/python/lib/

Tests:
Executed a simple Kafka spark job (compiled against
Spark 2.3.2) to verify if everything is ok.
If we don't recompile then we get java.lang.AbstractMethodError.

Change-Id: Ifd25f63299fc77809e1d0fd34e5a3662c11214eb