DSP-11503 downgrade akka
newer akka causes problems when assembled into fatjar.

The error is:

[2016-12-19 15:33:52,515] ERROR o.a.s.d.DseSparkSubmitBootstrapper [] [] - Failed to start or submit Spark application
java.lang.VerifyError: Inconsistent stackmap frames at branch target 152
Exception Details:
  Location:
    akka/dispatch/Mailbox.processAllSystemMessages()V @152: getstatic
  Reason:
    Type top (current frame, locals[9]) is not assignable to 'akka/dispatch/sysmsg/SystemMessage' (stack map, locals[9])
(...)