fix(file-cache): Create missing directories
If directory specified for the file caching doesn't exist,
Jobserver should create it instead of failing the operation.

As cacheBinary is a protected method, new spec class for
the test of modified FileCacher version is introduced.

Seen exception:
   java.io.IOException: No such file or directory

Change-Id: Id443606eb0be5b41ac0df1e73ef22f5ba286f79f