fix(test): Fix spark.driver.host to localhost
In some cases, we receive connection refused
exceptions during tests. The exception is
java.io.IOException: Failed to connect to /172.18.3.2:34706

Hardcoding the driver host to localhost fixes
the problem.

Aroung 7 testcases were failing due to this
problem and it was only noticed after moving
to sbt version 1.2.6.

Change-Id: I5ce867d47a3f7f14c2d0999dddfa317bf5d32bdb